#!/usr/local/bin/perl -w

# Check the sheband line, and then just call this script from your .profile

use strict;
use Date::Convert::French_Rev;

my ($y, $m, $d) = (localtime())[5, 4, 3];
my $day =  new Date::Convert::Gregorian $y + 1900, $m + 1, $d;
convert Date::Convert::French_Rev $day;
print $day->date_string("Today is %A %d %B %EY, %Ej%n");

